# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cff5618d374b3f2420f86f40d0b86b9082039fad5428df4d2612d7213bcf3d3e400b8226986dda4d141df640728c39f4b026853730bdb61689aeb6f8d1c1e92d

test:
  secret_key_base: edcb5cddf2219a73b12d39041a05d7ea3fe185ad3ab3afd5a926e52663de8981544d2c1d5ef78c454487f61485e99b042782a3dca73f2cc4f280aa971bd5fa5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
